services:                                                                                                   
    db-admin:
        # Define pgAdmin interface
        image: "crunchydata/crunchy-pgadmin4:latest"
        container_name: "compose_environments_pgadmin"
        environment:
            PGADMIN_SETUP_EMAIL: brian.armolla@gmail.com
            PGADMIN_SETUP_PASSWORD: "!r4nd0m"
        ports:
            - "5050:5050"
    db:
        # Define database
        image: "registry.redhat.io/rhel8/postgresql-13"
        container_name: "compose_environments_postgresql"
        environment:
            POSTGRESQL_USER: backend
            POSTGRESQL_PASSWORD: backend
            POSTGRESQL_DATABASE: example
        ports:
            - "5432:5432"
        #volumes:
        #    - ./database_scripts:/opt/app-root/src/postgresql-start:Z
        #    - rpi:/var/lib/pgsql/data

#volumes:
#    #Define persistent volume
#    rpi: {}
